site_name: Flaskstarter
repo_url: https://github.com/felipebastos/python-basic
repo_name: felipebastos/python-basic
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/flaskstarter.png
  favicon: assets/flaskstarter.png

plugins: 
  - mkdocstrings

markdown_extensions:
  - attr_list
